# Generated by Django 6.0.4 on 2026-04-20 04:00

from django.db import migrations, models


def backfill_legacy_source_format(apps, schema_editor):
    PracticeProblem = apps.get_model('api', 'PracticeProblem')
    PracticeProblem.objects.filter(
        source_text='',
        compiled_latex='',
    ).exclude(
        question_latex='',
        answer_latex='',
    ).update(source_format='latex_legacy')


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_cheatsheet_selected_formulas'),
    ]

    operations = [
        migrations.AddField(
            model_name='practiceproblem',
            name='compiled_latex',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='practiceproblem',
            name='label',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='practiceproblem',
            name='source_format',
            field=models.CharField(default='simple_v1', max_length=20),
        ),
        migrations.AddField(
            model_name='practiceproblem',
            name='source_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='practiceproblem',
            name='question_latex',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.RunPython(backfill_legacy_source_format, migrations.RunPython.noop),
    ]
